syntax on
filetype off 



set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/JavaScript-Indent'
Plugin 'Valloric/YouCompleteMe'


call vundle#end()  


filetype plugin indent on   



autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
map <C-n> :NERDTreeToggle<CR>
set number
set encoding=utf-8
set fileencoding=utf-8
filetype plugin indent on
set tabstop=4 shiftwidth=4
set expandtab
set nohlsearch
set incsearch
set ignorecase
set smartcase
set nocompatible
